apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  labels:
    app: rstudio
spec:
  type: NodePort
  ports:
    - port: 8787
      nodePort: 30001
      name: http
  selector:
    app: rstudio
