apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name}}-rstudio-pod
  labels:
    app: rstudio
spec:
  containers:
    - name: rstudio
      image: {{ .Values.cluster.rstudioImage }}
      tag: {{ .Values.cluster.rstudioTag}}
      env:
        - name: {{ .Values.rstudioConfig.env.name }}
          value: {{ .Values.rstudioConfig.env.value }}
      ports:
        - containerPort: {{ .Values.rstudioConfig.port }}
      imagePullPolicy: {{ .Values.rstudioConfig.pullPolicy }}
  restartPolicy: {{ .Values.clusterConfig.restartPolicy}}
