apiVersion: v1
kind: Pod
metadata:
  name: rstudio-pod
  labels:
    app: {{ .Values.rstudio_app_name }}
spec:
  containers:
    - name: {{ .Values.rstudio_app_name }}
      image: {{ .Values.image.repository }}
      env:
        - name: {{ .Values.env.name }}
          value: {{ .Values.env.value }}
      ports:
        - containerPort: {{ .Values.service.port }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
  restartPolicy: "OnFailure"
  
